using IVSoftware.WinOS.MSTest.Extensions;
using Newtonsoft.Json;
using static IVSoftware.Portable.Common.Common;

namespace IVSoftware.Portable.Common.MSTest
{
    [TestClass]
    public class TestClass_TypeCache
    {

        [TestMethod]
        public void Test_TypeCache()
        {
            string actual, expected;

            var types = TypeCache.Values;

            actual = JsonConvert.SerializeObject(types, Formatting.Indented);
            actual.ToClipboardExpected();
            { }
            expected = @" 
[
  ""Internal.Console, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"",
  ""Internal.Console+Error, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"",
  ""IVSoftware.Portable.Common.MSTest.TestClass_Throw, IVSoftware.Portable.Common.MSTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.MSTest.TestClass_TypeCache, IVSoftware.Portable.Common.MSTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Extensions, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.ITypeCache, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.TypeCacheMatchMode, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Common, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.TypeCacheExtensions, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.CanonicalAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.CarefulAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.ProbationaryAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.ScaffoldingAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.UnsupportedAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.IndexerAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.PolicyAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.PolicyEnforcementAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.NotFlagsAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.ClaimAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Exceptions.Advisory, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Exceptions.ThrowOrAdvise, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Exceptions.ThrowableStatus, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Exceptions.ThrowToStringFormat, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Exceptions.Throw, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Exceptions.ThrowExtensions, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.WinOS.MSTest.Extensions.Extensions, IVSoftware.WinOS.MSTest.Extensions, Version=1.0.8.0, Culture=neutral, PublicKeyToken=61187cbbe9faa94a""
]"
            ;
            Assert.AreEqual(
                expected.NormalizeResult(),
                actual.NormalizeResult(),
                "Expecting json serialization to match."
            );

            "Newtonsoft".AppendNamespaceToCache();

            actual = JsonConvert.SerializeObject(types, Formatting.Indented);
            actual.ToClipboardExpected();
            { }
            expected = @" 
[
  ""Internal.Console, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"",
  ""Internal.Console+Error, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e"",
  ""IVSoftware.Portable.Common.MSTest.TestClass_Throw, IVSoftware.Portable.Common.MSTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.MSTest.TestClass_TypeCache, IVSoftware.Portable.Common.MSTest, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Extensions, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.ITypeCache, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.TypeCacheMatchMode, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Common, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.TypeCacheExtensions, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.CanonicalAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.CarefulAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.ProbationaryAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.ScaffoldingAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.UnsupportedAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.IndexerAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.PolicyAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.PolicyEnforcementAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.NotFlagsAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Attributes.ClaimAttribute, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Exceptions.Advisory, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Exceptions.ThrowOrAdvise, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Exceptions.ThrowableStatus, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Exceptions.ThrowToStringFormat, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Exceptions.Throw, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.Portable.Common.Exceptions.ThrowExtensions, IVSoftware.Portable.Common, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null"",
  ""IVSoftware.WinOS.MSTest.Extensions.Extensions, IVSoftware.WinOS.MSTest.Extensions, Version=1.0.8.0, Culture=neutral, PublicKeyToken=61187cbbe9faa94a"",
  ""Newtonsoft.Json.ConstructorHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.DateFormatHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.DateParseHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.DateTimeZoneHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.DefaultJsonNameTable, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.DefaultValueHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.FloatFormatHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.FloatParseHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Formatting, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.IArrayPool`1, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.IJsonLineInfo, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonArrayAttribute, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonConstructorAttribute, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonContainerAttribute, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonConvert, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonConverter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonConverter`1, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonConverterAttribute, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonConverterCollection, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonDictionaryAttribute, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonException, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonExtensionDataAttribute, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonIgnoreAttribute, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonNameTable, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonObjectAttribute, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonPropertyAttribute, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonReader, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonReaderException, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonRequiredAttribute, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonSerializationException, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonSerializer, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonSerializerSettings, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonTextReader, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonTextWriter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonToken, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonValidatingReader, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonWriter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.JsonWriterException, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.MemberSerialization, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.MetadataPropertyHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.MissingMemberHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.NullValueHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.ObjectCreationHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.PreserveReferencesHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.ReferenceLoopHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Required, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.StringEscapeHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.TypeNameAssemblyFormatHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.TypeNameHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.WriteState, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.CamelCaseNamingStrategy, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.CamelCasePropertyNamesContractResolver, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.DefaultContractResolver, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.DefaultNamingStrategy, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.DefaultSerializationBinder, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.DiagnosticsTraceWriter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.ErrorContext, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.ErrorEventArgs, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.ExpressionValueProvider, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.IAttributeProvider, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.IContractResolver, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.IReferenceResolver, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.ISerializationBinder, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.ITraceWriter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.IValueProvider, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.JsonArrayContract, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.JsonContainerContract, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.SerializationCallback, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.SerializationErrorCallback, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.ExtensionDataSetter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.ExtensionDataGetter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.JsonContract, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.JsonDictionaryContract, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.JsonDynamicContract, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.JsonISerializableContract, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.JsonLinqContract, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.JsonObjectContract, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.JsonPrimitiveContract, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.JsonProperty, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.JsonPropertyCollection, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.JsonStringContract, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.KebabCaseNamingStrategy, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.MemoryTraceWriter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.NamingStrategy, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.ObjectConstructor`1, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.OnErrorAttribute, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.ReflectionAttributeProvider, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.ReflectionValueProvider, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Serialization.SnakeCaseNamingStrategy, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Schema.Extensions, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Schema.JsonSchema, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Schema.JsonSchemaException, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Schema.JsonSchemaGenerator, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Schema.JsonSchemaResolver, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Schema.JsonSchemaType, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Schema.UndefinedSchemaIdHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Schema.ValidationEventArgs, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Schema.ValidationEventHandler, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.CommentHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.DuplicatePropertyNameHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.Extensions, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.IJEnumerable`1, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.JArray, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.JConstructor, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.JContainer, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.JEnumerable`1, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.JObject, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.JProperty, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.JPropertyDescriptor, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.JRaw, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.JsonLoadSettings, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.JsonMergeSettings, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.JsonSelectSettings, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.JToken, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.JTokenEqualityComparer, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.JTokenReader, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.JTokenType, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.JTokenWriter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.JValue, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.LineInfoHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.MergeArrayHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Linq.MergeNullValueHandling, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Converters.BinaryConverter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Converters.BsonObjectIdConverter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Converters.CustomCreationConverter`1, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Converters.DataSetConverter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Converters.DataTableConverter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Converters.DateTimeConverterBase, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Converters.DiscriminatedUnionConverter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Converters.EntityKeyMemberConverter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Converters.ExpandoObjectConverter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Converters.IsoDateTimeConverter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Converters.JavaScriptDateTimeConverter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Converters.KeyValuePairConverter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Converters.RegexConverter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Converters.StringEnumConverter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Converters.UnixDateTimeConverter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Converters.VersionConverter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Converters.XmlNodeConverter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Bson.BsonObjectId, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Bson.BsonReader, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed"",
  ""Newtonsoft.Json.Bson.BsonWriter, Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed""
]"
            ;
            Assert.AreEqual(
                expected.NormalizeResult(),
                actual.NormalizeResult(),
                "Expecting namespace appended."
            );
        }
    }
}
